
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
import tkinter as tk
from tkinter import Tk, Canvas, Button, PhotoImage, ttk, messagebox


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"D:\Python\PPLJ_GUI\assets")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("512x384")
window.configure(bg="#FFFFFF")


canvas = Canvas(window, bg="#FFFFFF", height=384, width=512, bd=0, highlightthickness=0, relief="ridge")
canvas.place(x=0, y=0)

canvas.create_rectangle(78.0, 97.0, 433.0, 347.0, fill="#D9D9D9", outline="")

image_image_1 = PhotoImage(file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(62.0, 33.0, image=image_image_1)

canvas.create_rectangle(125.0, 0.0, 512.0, 67.0, fill="#28003A", outline="")

canvas.create_text(204.0, 106.0, anchor="nw", text="Sign In", fill="#000000", font=("Inter", 32 * -1))
canvas.create_text(180.0, 262.0, anchor="nw", text="New Account?", fill="#000000", font=("Inter", 12 * -1))
#canvas.create_text(260.0, 262.0, anchor="nw", text="Sign up here", fill="#0084FF", font=("Inter", 12 * -1))
sign_up_text = ttk.Label(window, text="Sign up here", background="#D9D9D9", foreground="#0084FF", font=("Inter", 12 * -1), cursor="hand2")
sign_up_text.place(x=260.0, y=260.0)
def to_sign_up_page(event):
    print("To Sign Up Page")
    #Ke halaman sign up
def bold_sign_up_text(event):
    sign_up_text.configure(font=("Inter", 12 * -1, 'bold'))
def normalize_sign_up_text(event):
    sign_up_text.configure(font=("Inter", 12 * -1))
sign_up_text.bind("<Button-1>", to_sign_up_page)
sign_up_text.bind("<Enter>", bold_sign_up_text)
sign_up_text.bind("<Leave>", normalize_sign_up_text)

username = tk.StringVar()
password = tk.StringVar()

# ==================================Bagian Entry Password================================
password_entry = ttk.Entry(canvas, textvariable=password, foreground="gray")
password_entry.place(x=156.0, y=208.0, width=200.0, height=40.0)
password_entry.insert(0, "Password")
def password_in_focus(event):
    if password.get() == "Password":
        password_entry.delete(0, tk.END)
        password_entry.configure(foreground="black", show='*')
def password_out_focus(event):
    if password.get() == "":
        password_entry.insert(0, "Password")
        password_entry.configure(foreground="gray", show='')
password_entry.bind("<FocusIn>", password_in_focus)
password_entry.bind("<FocusOut>", password_out_focus)
# ========================================================================================

# ==================================Bagian Entry Username=================================
username_entry = ttk.Entry(canvas, textvariable=username, foreground="gray")
username_entry.place(x=156.0, y=152.0, width=200.0, height=40.0)
username_entry.insert(0, "Username")
def username_in_focus(event):
    if username.get() == "Username":
        username_entry.delete(0, tk.END)
        username_entry.configure(foreground="black")
def username_out_focus(event):
    if username.get() == "":
        username_entry.insert(0, "Username")
        username_entry.configure(foreground="gray")
username_entry.bind("<FocusIn>", username_in_focus)
username_entry.bind("<FocusOut>", username_out_focus)
# ========================================================================================

# ==================================Bagian Sign In========================================
button_image_1 = PhotoImage(file=relative_to_assets("button_1.png"))
button_1 = Button(image=button_image_1,borderwidth=0,highlightthickness=0,command=lambda: sign_in_callback(),relief="flat", cursor="hand2")
button_1.place(x=156.0, y=285.0, width=200.0, height=40.0)
def sign_in_callback():
    if username.get() == "Username" or password.get() == "Password":
        msg = messagebox.showinfo("Notice", "Username or Password empty or invalid!")
    else:
        msg = messagebox.showinfo("Notice", "Signed in!")
        #if msg == "ok":
        #masuk ke halaman pilih role (client)
# ========================================================================================

window.resizable(False, False)
window.mainloop()
